name: Publish Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-release.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: tailscale-debug-apk
          run-id: 37142652763
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: "Tailscale Proxy APK v1.0.0"
          files: tailscale-debug.apk
